insert into public.indicators (id, user_id, indicator, name_indicator, perspective, name_perspective, objective_strategy, name_strategy, indicator_strategy, name_indicator_strategy, status, created_at, updated_at)
values  (827, 1, '827', 'Convocar y desarrollar los comites directivos  ', '0', '3. DESARROLLO INSTITUCIONAL', 'Objetivo 6 Fortalecer el modelo de operación institucional para lograr una gestión efectiva orientada a resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I49 Diseñar e implementar
estrategia de articulación de los
servicios misionales', null, 'Activo', null, null),
        (14, 1, '14', 'Aprendices con contrato de aprendizaje voluntario', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I16. Fortalecimiento de las estrategias de relacionamiento empresarial  para incrementar el número de empresas objeto de regulación, de acuerdo con lo establecido en la Ley 789 de 2002 y Decretos reglamentarios vigentes a través de las regionales.', null, 'Activo', null, null),
        (779, 1, '779', 'Reporte trimestral de quejas y/o informes que ingresan a la Oficina de Control Interno Disciplinario
', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'N/A', null, 'Activo', null, null),
        (283, 1, '283', 'Vacantes APE', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I11. Diseñar e implementar  acciones para el fortalecimiento de la calidad y pertinencia de la gestión y colocación de Empleo', null, 'Activo', null, null),
        (828, 1, '828', 'Convocar y desarrollar los encuentros nacionales de Directores Regionales y Subdirectores de Centro', '0', '3. DESARROLLO INSTITUCIONAL', 'Objetivo 6 Fortalecer el modelo de operación institucional para lograr una gestión efectiva orientada a resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I49 Diseñar e implementar
estrategia de articulación de los
servicios misionales', null, 'Activo', null, null),
        (497, 1, '497', 'Personas Formadas y Entrenadas en Colombia en el Marco de Proyectos Internacionales', '0', '2. MISIÓN', 'MI-O5. Contribuir a la calidad y pertinencia de los servicios institucionales a partir de la gestión de alianzas estratégicas y/o convenios nacionales e internacionales', '-', 'MI-O5-I30. Fortalecer los convenios nacionales e internacionales de acuerdo con el Esquema de Movilidad Educativa, Formativa, laboral – EMEF, entre otros.', null, 'Activo', null, null),
        (780, 1, '780', 'Reporte trimestral de autos de apertura de indagaciones previas e investigaciones disciplinarias.
', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'N/A', null, 'Activo', null, null),
        (284, 1, '284', 'Inscritos en la APE', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I11. Diseñar e implementar  acciones para el fortalecimiento de la calidad y pertinencia de la gestión y colocación de Empleo', null, 'Activo', null, null),
        (829, 1, '829', 'Alianzas nacionales e internacionales suscritas y/o fortalecidas', '0', '3. DESARROLLO INSTITUCIONAL', 'Objetivo 6 Fortalecer el modelo de operación institucional para lograr una gestión efectiva orientada a resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I49 Diseñar e implementar
estrategia de articulación de los
servicios misionales', null, 'Activo', null, null),
        (591, 1, '591', 'Alianzas estratégicas, convenios y/o proyectos nacionales e internacionales suscritos y/o fortalecidos por el SENA', '0', '2. MISIÓN', 'MI-O5. Contribuir a la calidad y pertinencia de los servicios institucionales a partir de la gestión de alianzas estratégicas y/o convenios nacionales e internacionales', '-', 'MI-O5-I30. Fortalecer los convenios nacionales e internacionales de acuerdo con el Esquema de Movilidad Educativa, Formativa, laboral – EMEF, entre otros.', null, 'Activo', null, null),
        (781, 1, '781', 'Reporte trimestral de procesos archivados, anulados, remitidos por competencia y autos inhibitorios
', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'N/A', null, 'Activo', null, null),
        (516, 1, '516', 'Divulgar información de la gestión institucional para los grupos de valor internos del SENA.', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I51. Fortalecer la dimensión información y comunicación a través  productos y canales de comunicación accesibles, acciones articuladas de imagen corporativa y  una imagen de marca SENA incluyente, sostenible  y transparente', null, 'Activo', null, null),
        (542, 1, '542', 'Informe de Seguimiento realizados a las colocaciones a nivel Regional APE Agencia', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I11. Diseñar e implementar  acciones para el fortalecimiento de la calidad y pertinencia de la gestión y colocación de Empleo', null, 'Activo', null, null),
        (592, 1, '592', 'Aportes efectuados en especie por los aliados de cooperación mediante las alianzas estratégicas, convenios y/o proyectos del SENA', '0', '2. MISIÓN', 'MI-O5. Contribuir a la calidad y pertinencia de los servicios institucionales a partir de la gestión de alianzas estratégicas y/o convenios nacionales e internacionales', '-', 'MI-O5-I31. Incorporar convenios en  economía popular, economía campesina, habilidades digitales y jóvenes en paz', null, 'Activo', null, null),
        (782, 1, '782', 'Reporte trimestral de pliego de cargos remitidos a la fase de juzgamiento
', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'N/A', null, 'Activo', null, null),
        (517, 1, '517', 'Divulgar información de la gestión  institucional para los grupos de valor externos.', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I51. Fortalecer la dimensión información y comunicación a través  productos y canales de comunicación accesibles, acciones articuladas de imagen corporativa y  una imagen de marca SENA incluyente, sostenible  y transparente', null, 'Activo', null, null),
        (615, 1, '615', 'Informes de Seguimiento realizados a la ejecución operativa y presupuestal  a nivel Regional y de la Coordinación Nacional en el marco de la APE', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I11. Diseñar e implementar  acciones para el fortalecimiento de la calidad y pertinencia de la gestión y colocación de Empleo', null, 'Activo', null, null),
        (666, 1, '666', 'Empresas en Fortalecimiento', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I13. Fortalecimiento de la atención empresarial', null, 'Activo', null, null),
        (783, 1, '783', 'Porcentaje de cumplimiento de la estrategia de prevención de la vigencia
', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'N/A', null, 'Activo', null, null),
        (740, 1, '740', 'Informes  elaborados sobre la tendencia ocupacional según cifras de la Agencia Pública de Empleo elaborados', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I11. Diseñar e implementar  acciones para el fortalecimiento de la calidad y pertinencia de la gestión y colocación de Empleo', null, 'Activo', null, null),
        (545, 1, '545', 'Informes de Seguimiento realizados a la ejecución operativa y presupuestal  a nivel Regional y de la Coordinación Nacional en el marco del Programa de Emprendimiento', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I12. Diseñar e implementar acciones para el fortalecimiento de la calidad y pertinencia de emprendimiento', null, 'Activo', null, null),
        (871, 1, '871', 'Número de Empleos potenciales directos de economía popular a través del Fondo Emprender  - Full Popular', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'VA-O1-I2. Implementar la estrategia de atención integral, diferencial  e incluyente para el sector de la economía popular - Full Popular', null, 'Activo', null, null),
        (598, 1, '598', 'Empresas creadas por comunidades NARP', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'N/A', null, 'Activo', null, null),
        (872, 1, '872', 'Personas víctimas del desplazamiento forzado orientadas a través de la APE', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I11. Diseñar e implementar  acciones para el fortalecimiento de la calidad y pertinencia de la gestión y colocación de Empleo', null, 'Activo', null, null),
        (599, 1, '599', 'Empresas fortalecidas por comunidades NARP', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'N/A', null, 'Activo', null, null),
        (873, 1, '873', 'Personas  víctimas  de  desplazamiento  forzado  que  acceden  a  programas  de  formación profesional integral', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'VA-O1-I3. Brindar  atención integral, diferencial  e incluyente  a las personas víctimas del conflicto armado y a los firmantes de paz, que contribuya a  la garantía de sus derechos sociales y económicos,  a la  transformación productiva y equitativa de l', null, 'Activo', null, null),
        (625, 1, '625', 'Acompañamiento en la adopción del Modelo de Cualificaciones del SENA', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I17. Diseñar y desarrollar un Modelo  Institucional que facilite la transición del SENA al Sistema Nacional de Cualificaciones.', null, 'Activo', null, null),
        (485, 1, '485', 'Porcentaje de cumplimiento en la ejecución de trabajos de aseguramiento y consultoría del plan anual de auditoría aprobado por el Comité Institucional de Coordinación de Control Interno', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I40. Mejorar y proteger el valor de la Entidad con la evaluación independiente mediante servicios de aseguramiento y consultoría de los procesos de control, gestión de riesgos y gobierno institucional, lo que contribuye al logro de los objetivos.​', null, 'Activo', null, null),
        (874, 1, '874', 'Número de planes de negocio formulados por víctimas del desplazamiento forzado.', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I12. Diseñar e implementar acciones para el fortalecimiento de la calidad y pertinencia de emprendimiento', null, 'Activo', null, null),
        (603, 1, '603', 'Evolución del cierre de brechas del Índice de Transformación Digital del SENA', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I43. Plan Estratégico de Tecnologías de la Información y las Comunicaciones (PETI)', null, 'Activo', null, null),
        (835, 1, '835', 'Número de beneficiarios de la Formación Especializada para la Economía Campesina', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'VA-O1-I1. Implementar la estrategia de atención integral, diferencial  e incluyente para el sector de la economía campesina - CampeSENA', null, 'Activo', null, null),
        (520, 1, '520', 'Porcentaje de cobertura en créditos de vivienda de Afiliados FNV', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I45. Plan Estratégico de Talento Humano', null, 'Activo', null, null),
        (875, 1, '875', 'Número de mujeres víctimas de desplazamiento forzado orientadas', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'VA-O1-I8. Brindar  atención integral y diferencial a las mujeres', null, 'Activo', null, null),
        (551, 1, '551', 'Porcentaje de Incidencia en las competencias del Talento Humano', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I45. Plan Estratégico de Talento Humano', null, 'Activo', null, null),
        (836, 1, '836', 'Número de cupos para beneficiarios de la Formación Especializada para la Economía Campesina', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'VA-O1-I1. Implementar la estrategia de atención integral, diferencial  e incluyente para el sector de la economía campesina - CampeSENA', null, 'Activo', null, null),
        (632, 1, '632', 'Porcentaje de Capacitación para Servidores Públicos', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I45. Plan Estratégico de Talento Humano', null, 'Activo', null, null),
        (876, 1, '876', 'Número de mujeres víctimas de otros hechos victimizantes que han accedido a formación profesional integral.', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'VA-O1-I8. Brindar  atención integral y diferencial a las mujeres', null, 'Activo', null, null),
        (43, 1, '43', 'Cantidad de Informes producidos de estadísticas', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I44. Implementación del Plan Estadístico Institucional', null, 'Activo', null, null),
        (837, 1, '837', 'Número de asociaciones campesinas y/o agropecuarias beneficiarias de la  Formación Especializada para la Economía Campesina', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'VA-O1-I1. Implementar la estrategia de atención integral, diferencial  e incluyente para el sector de la economía campesina - CampeSENA', null, 'Activo', null, null),
        (430, 1, '430', 'Número de seguimientos al Plan de Acción de la entidad', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'N/A', null, 'Activo', null, null),
        (877, 1, '877', 'Planes de negocio formulados por mujeres víctimas del desplazamiento forzado.', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'VA-O1-I8. Brindar  atención integral y diferencial a las mujeres', null, 'Activo', null, null),
        (534, 1, '534', 'Gestión de actividades para formulación, presentación y seguimiento  al Anteproyecto de Presupuesto y Proyectos de Inversión del SENA para la proxima vigencia', '0', '4. RECURSOS', 'RE-O7. Administrar los recursos institucionales con criterios de oportunidad, austeridad, eficiencia y eficacia ', '-', 'RE-O7-I56. Fortalecimiento de la política de Gestión presupuestal y eficiencia del gasto público', null, 'Activo', null, null),
        (838, 1, '838', 'Número de Certificatones de Competencia Laboral realizadas a mujeres', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'VA-O1-I8. Brindar  atención integral y diferencial a las mujeres', null, 'Activo', null, null),
        (539, 1, '539', 'Cumplimiento de requisitos legales ambientales', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'N/A', null, 'Activo', null, null),
        (878, 1, '878', 'Número de cupos de formación profesional integral para personas con discapacidad', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'VA-O1-I4. Implementar la Política Institucional de Atención a Personas con Discapacidad', null, 'Activo', null, null),
        (540, 1, '540', 'Estrategias que promuevan el ahorro en consumos de Energía, desplegadas', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'N/A', null, 'Activo', null, null),
        (839, 1, '839', 'Número de Beneficiarios del Programa de Formación Continua Especializada', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I13. Fortalecimiento de la atención empresarial', null, 'Activo', null, null),
        (879, 1, '879', 'Número de Personas con discapacidad que recibieron capacitación para el Trabajo', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'VA-O1-I4. Implementar la Política Institucional de Atención a Personas con Discapacidad', null, 'Activo', null, null),
        (840, 1, '840', 'Número de Cupos para beneficiarios del Programa de Formación Continua Especializada', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I13. Fortalecimiento de la atención empresarial', null, 'Activo', null, null),
        (880, 1, '880', 'Número de Mujeres beneficiadas por convocatorias Fondo Emprender ', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'VA-O1-I8. Brindar  atención integral y diferencial a las mujeres', null, 'Activo', null, null),
        (841, 1, '841', 'Número de Empresas Beneficiadas por el Programa de Formación Continua Especializada', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I13. Fortalecimiento de la atención empresarial', null, 'Activo', null, null),
        (881, 1, '881', 'Número de colocaciones de mujeres a través de la Agencia Pública de Empleo', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'VA-O1-I8. Brindar  atención integral y diferencial a las mujeres', null, 'Activo', null, null),
        (842, 1, '842', 'Número de pilotos de evaluación y certificación de competencias laborales ejecutados, de acuerdo con las políticas del Sistema Nacional de Cualificaciones', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I17. Diseñar y desarrollar un Modelo  Institucional que facilite la transición del SENA al Sistema Nacional de Cualificaciones.', null, 'Activo', null, null),
        (882, 1, '882', 'Vinculación laboral de los Titulados y certificados de la Formación Profesional que consiguen trabajo a los 6 meses de egresados ', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I10. Diseñar e implementar estrategias para fortalecer la vinculación laboral de los titulados certificados de la Formación Profesional', null, 'Activo', null, null),
        (843, 1, '843', 'Número de Catálogos de Cualificaciones elaborados', '0', '2. MISIÓN', 'MI-O3. Aportar al fortalecimiento de la gestión del capital humano en el país, mejorando la pertinencia y calidad de los servicios institucionales, 
 con el fin de favorecer la gestión y cierre de brechas de capital humano,  la productividad laboral, la c', '-', 'MI-O3-I21. Diseñar y desarrollar un Modelo  Institucional que facilite la transición del SENA al Sistema Nacional de Cualificaciones.', null, 'Activo', null, null),
        (883, 1, '883', 'Informe de seguimiento a la tasa de Vinculación laboral de los Titulados y certificados de la Formación Profesional que consiguen trabajo a los 6 meses de egresados', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I10. Diseñar e implementar estrategias para fortalecer la vinculación laboral de los titulados certificados de la Formación Profesional', null, 'Activo', null, null),
        (844, 1, '844', 'Número de empresas orientadas para la implementación de la metodología de la gestión del talento humano por competencias', '0', '2. MISIÓN', 'MI-O3. Aportar al fortalecimiento de la gestión del capital humano en el país, mejorando la pertinencia y calidad de los servicios institucionales, 
 con el fin de favorecer la gestión y cierre de brechas de capital humano,  la productividad laboral, la c', '-', 'MI-O3-I21. Diseñar y desarrollar un Modelo  Institucional que facilite la transición del SENA al Sistema Nacional de Cualificaciones.', null, 'Activo', null, null),
        (884, 1, '884', 'Número de colocaciones a través de la Agencia Pública de Empleo', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I11. Diseñar e implementar  acciones para el fortalecimiento de la calidad y pertinencia de la gestión y colocación de Empleo', null, 'Activo', null, null),
        (845, 1, '845', 'Número de eventos de sensibilización y transferencia de conocimiento sobre el Sistema Nacional de Cualificaciones', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I48. Diseñar y desarrollar un Modelo  Institucional que facilite la transición del SENA al Sistema Nacional de Cualificaciones.', null, 'Activo', null, null),
        (885, 1, '885', 'Número de Empresas con Asignación de Recursos para Sostenibilidad', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I13. Fortalecimiento de la atención empresarial', null, 'Activo', null, null),
        (846, 1, '846', 'Recaudo efectivo de procesos a favor ', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I41. Fortalecimiento de la capacidad institucional en materia de contratación pública, prevención del daño antijurídico y armonización de la normativa interna.', null, 'Activo', null, null),
        (886, 1, '886', 'Iniciativas productivas rurales y campesinas beneficiadas a través del programa SENA Emprende Rural ', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I12. Diseñar e implementar acciones para el fortalecimiento de la calidad y pertinencia de emprendimiento', null, 'Activo', null, null),
        (847, 1, '847', 'Implementación del Plan de Acción de la Política de Prevención del Daño Antijurídico (PPDA)', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I41. Fortalecimiento de la capacidad institucional en materia de contratación pública, prevención del daño antijurídico y armonización de la normativa interna.', null, 'Activo', null, null),
        (887, 1, '887', 'Número de informes de avance implementación de la política institucional de atención a personas con discapacidad', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'VA-O1-I4. Implementar la Política Institucional de Atención a Personas con Discapacidad', null, 'Activo', null, null),
        (848, 1, '848', 'Índice de actualización y compilación normativa', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I41. Fortalecimiento de la capacidad institucional en materia de contratación pública, prevención del daño antijurídico y armonización de la normativa interna.', null, 'Activo', null, null),
        (888, 1, '888', 'Número de empresas creadas por el Fondo Emprender', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I12. Diseñar e implementar acciones para el fortalecimiento de la calidad y pertinencia de emprendimiento', null, 'Activo', null, null),
        (849, 1, '849', 'Seguimiento a los trámites realizados a la Coordinación de Recursos y Peticiones
', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I41. Fortalecimiento de la capacidad institucional en materia de contratación pública, prevención del daño antijurídico y armonización de la normativa interna.', null, 'Activo', null, null),
        (889, 1, '889', 'Número de empleos potenciales directos a través de Fondo Emprender  (incluye autoempleo)', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I12. Diseñar e implementar acciones para el fortalecimiento de la calidad y pertinencia de emprendimiento', null, 'Activo', null, null),
        (850, 1, '850', 'Actualización y socializción en lineamientos de contratación administrativa.', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I41. Fortalecimiento de la capacidad institucional en materia de contratación pública, prevención del daño antijurídico y armonización de la normativa interna.', null, 'Activo', null, null),
        (890, 1, '890', 'Organizaciones del programa SENA Emprende Rural beneficiadas a través de servicios complementarios de apoyo a la comercialización de productos', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I12. Diseñar e implementar acciones para el fortalecimiento de la calidad y pertinencia de emprendimiento', null, 'Activo', null, null),
        (851, 1, '851', 'Cumplimiento de socializaciones en buenas prácticas', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I41. Fortalecimiento de la capacidad institucional en materia de contratación pública, prevención del daño antijurídico y armonización de la normativa interna.', null, 'Activo', null, null),
        (891, 1, '891', 'Informes de Seguimiento realizados a la ejecución operativa y presupuestal  de población víctima de desplazamiento forzado a nivel Regional y de la Coordinación Nacional en el marco de la APE', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I11. Diseñar e implementar  acciones para el fortalecimiento de la calidad y pertinencia de la gestión y colocación de Empleo', null, 'Activo', null, null),
        (892, 1, '892', 'Número de Empresas  creadas en Economía popular a través del Fondo Emprender - Full Popular', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'VA-O1-I2. Implementar la estrategia de atención integral, diferencial  e incluyente para el sector de la economía popular - Full Popular', null, 'Activo', null, null),
        (893, 1, '893', 'Número de alianzas gestionadas para el fortalecimiento del emprendimiento rural', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I12. Diseñar e implementar acciones para el fortalecimiento de la calidad y pertinencia de emprendimiento', null, 'Activo', null, null),
        (807, 1, '807', 'Total de Aprendices con Contrato de Aprendizaje', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I16. Fortalecimiento de las estrategias de relacionamiento empresarial  para incrementar el número de empresas objeto de regulación, de acuerdo con lo establecido en la Ley 789 de 2002 y Decretos reglamentarios vigentes a través de las regionales.', null, 'Activo', null, null),
        (894, 1, '894', 'Informes de Seguimiento realizados a la ejecución operativa y presupuestal  a nivel Regional y de la Coordinación Nacional en el marco del Programa SENA Emprende rural', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I12. Diseñar e implementar acciones para el fortalecimiento de la calidad y pertinencia de emprendimiento', null, 'Activo', null, null),
        (808, 1, '808', 'Aprendices con Contrato de Aprendizaje no SENA', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I16. Fortalecimiento de las estrategias de relacionamiento empresarial  para incrementar el número de empresas objeto de regulación, de acuerdo con lo establecido en la Ley 789 de 2002 y Decretos reglamentarios vigentes a través de las regionales.', null, 'Activo', null, null),
        (809, 1, '809', 'Empresas con cuota reguladas', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I16. Fortalecimiento de las estrategias de relacionamiento empresarial  para incrementar el número de empresas objeto de regulación, de acuerdo con lo establecido en la Ley 789 de 2002 y Decretos reglamentarios vigentes a través de las regionales.', null, 'Activo', null, null),
        (810, 1, '810', 'Empresas con cuota voluntaria', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I16. Fortalecimiento de las estrategias de relacionamiento empresarial  para incrementar el número de empresas objeto de regulación, de acuerdo con lo establecido en la Ley 789 de 2002 y Decretos reglamentarios vigentes a través de las regionales.', null, 'Activo', null, null),
        (99, 1, '99', 'Movilidad Internacional', '0', '2. MISIÓN', 'MI-O5. Contribuir a la calidad y pertinencia de los servicios institucionales a partir de la gestión de alianzas estratégicas y/o convenios nacionales e internacionales', '-', 'MI-O5-I30. Fortalecer los convenios nacionales e internacionales de acuerdo con el Esquema de Movilidad Educativa, Formativa, laboral – EMEF, entre otros.', null, 'Activo', null, null),
        (811, 1, '811', 'Número de Aprendices SENA Con Contrato De Aprendizaje (Incluye contratos voluntarios)', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I16. Fortalecimiento de las estrategias de relacionamiento empresarial  para incrementar el número de empresas objeto de regulación, de acuerdo con lo establecido en la Ley 789 de 2002 y Decretos reglamentarios vigentes a través de las regionales.', null, 'Activo', null, null),
        (733, 1, '733', 'Porcentaje de Acciones ejecutadas en materia de Política de Integridad', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'N/A', null, 'Activo', null, null),
        (831, 1, '831', 'Suscripción de alianzas estrategicas nacionales de la Direción General ', '0', '2. MISIÓN', 'MI-O5. Contribuir a la calidad y pertinencia de los servicios institucionales a partir de la gestión de alianzas estratégicas y/o convenios nacionales e internacionales', '-', 'MI-O5-I30. Fortalecer los convenios nacionales e internacionales de acuerdo con el Esquema de Movilidad Educativa, Formativa, laboral – EMEF, entre otros.', null, 'Activo', null, null),
        (734, 1, '734', 'Porcentaje de Cumplimiento del Plan Anual de Trabajo de Seguridad y Salud en el Trabajo Nacional', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'N/A', null, 'Activo', null, null),
        (799, 1, '799', 'Empresas Nacientes Acompañadas en el Proceso de Emprendimiento y Asesoradas para su Ejecución', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I12. Diseñar e implementar acciones para el fortalecimiento de la calidad y pertinencia de emprendimiento', null, 'Activo', null, null),
        (731, 1, '731', 'Productos digitales propios generados y publicados por la Dirección General', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I51. Fortalecer la dimensión información y comunicación a través  productos y canales de comunicación accesibles, acciones articuladas de imagen corporativa y  una imagen de marca SENA incluyente, sostenible  y transparente', null, 'Activo', null, null),
        (800, 1, '800', 'Total Número de Colocaciones', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I11. Diseñar e implementar  acciones para el fortalecimiento de la calidad y pertinencia de la gestión y colocación de Empleo', null, 'Activo', null, null),
        (735, 1, '735', 'Porcentaje de Actividades programadas para determimar el porcentaje de satisfacción de los  beneficarios del SMA.', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I45. Plan Estratégico de Talento Humano', null, 'Activo', null, null),
        (801, 1, '801', 'Número de Colocaciones Egresados SENA', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I11. Diseñar e implementar  acciones para el fortalecimiento de la calidad y pertinencia de la gestión y colocación de Empleo', null, 'Activo', null, null),
        (732, 1, '732', 'Encuentro nacional comunicaciones 2024', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I51. Fortalecer la dimensión información y comunicación a través  productos y canales de comunicación accesibles, acciones articuladas de imagen corporativa y  una imagen de marca SENA incluyente, sostenible  y transparente', null, 'Activo', null, null),
        (802, 1, '802', 'Número de Colocaciones no SENA', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I11. Diseñar e implementar  acciones para el fortalecimiento de la calidad y pertinencia de la gestión y colocación de Empleo', null, 'Activo', null, null),
        (830, 1, '830', 'Porcentaje de avance en el diseño e implementación de la estrategia nacional de comunicaciones 2023 – 2026
', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I51. Fortalecer la dimensión información y comunicación a través  productos y canales de comunicación accesibles, acciones articuladas de imagen corporativa y  una imagen de marca SENA incluyente, sostenible  y transparente', null, 'Activo', null, null),
        (803, 1, '803', 'Tasa de Colocación', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I11. Diseñar e implementar  acciones para el fortalecimiento de la calidad y pertinencia de la gestión y colocación de Empleo', null, 'Activo', null, null),
        (737, 1, '737', 'Porcentaje de Cupos del Plan de Bienestar para Servidores Públicos', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I45. Plan Estratégico de Talento Humano', null, 'Activo', null, null),
        (832, 1, '832', 'Porcentaje de avance en la evolución de la implementación de plan estratégico del Talento Humano', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I45. Plan Estratégico de Talento Humano', null, 'Activo', null, null),
        (833, 1, '833', 'Porcentaje de avance Implementación Archivo Electrónico SENA', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I42. Generar estrategias para consolidar la gestión documental con fines de conservación, preservación y servicios de información y consulta de los documentos producidos y recibidos en el SENA.', null, 'Activo', null, null),
        (834, 1, '834', 'Porcentaje de implementación de Plan Institucional de Archivos de la Entidad ­PINAR', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I46. Plan Institucional de Archivos – PINAR', null, 'Activo', null, null),
        (865, 1, '865', 'Evolución del recaudo de recursos financieros', '0', '4. RECURSOS', 'RE-O7. Administrar los recursos institucionales con criterios de oportunidad, austeridad, eficiencia y eficacia ', '-', 'RE-O7-I58. Fomentar las acciones para el fortalecimiento del recaudo de recursos institucionales', null, 'Activo', null, null),
        (866, 1, '866', 'Evolución de cumplimiento del plan maestro de infraestructura', '0', '4. RECURSOS', 'RE-O7. Administrar los recursos institucionales con criterios de oportunidad, austeridad, eficiencia y eficacia ', '-', 'RE-O7-I54. Desarrollar el plan maestro de infraestructura.', null, 'Activo', null, null),
        (867, 1, '867', 'Evolución de la implementación del plan de austeridad del gasto ', '0', '4. RECURSOS', 'RE-O7. Administrar los recursos institucionales con criterios de oportunidad, austeridad, eficiencia y eficacia ', '-', 'RE-O7-I55. Plan de austeridad del gasto', null, 'Activo', null, null),
        (868, 1, '868', 'Evolución de la ejecución de los recursos financieros de funcionamiento e inversión (comprometido)', '0', '4. RECURSOS', 'RE-O7. Administrar los recursos institucionales con criterios de oportunidad, austeridad, eficiencia y eficacia ', '-', 'RE-O7-I55. Plan de austeridad del gasto', null, 'Activo', null, null),
        (758, 1, '758', 'Porcentaje de cumplimiento en el número de seguimientos al estado de avance de los planes de mejoramiento (AIG)', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I40. Mejorar y proteger el valor de la Entidad con la evaluación independiente mediante servicios de aseguramiento y consultoría de los procesos de control, gestión de riesgos y gobierno institucional, lo que contribuye al logro de los objetivos.​', null, 'Activo', null, null),
        (869, 1, '869', 'Evolución de la ejecución de los recursos financieros de funcionamiento e inversión (pagado)', '0', '4. RECURSOS', 'RE-O7. Administrar los recursos institucionales con criterios de oportunidad, austeridad, eficiencia y eficacia ', '-', 'RE-O7-I55. Plan de austeridad del gasto', null, 'Activo', null, null),
        (761, 1, '761', 'Nivel de madurez actividad de auditoría interna', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I40. Mejorar y proteger el valor de la Entidad con la evaluación independiente mediante servicios de aseguramiento y consultoría de los procesos de control, gestión de riesgos y gobierno institucional, lo que contribuye al logro de los objetivos.​', null, 'Activo', null, null),
        (762, 1, '762', 'Porcentaje de cumplimiento desarrollo subcomité de control interno - Regionales', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I40. Mejorar y proteger el valor de la Entidad con la evaluación independiente mediante servicios de aseguramiento y consultoría de los procesos de control, gestión de riesgos y gobierno institucional, lo que contribuye al logro de los objetivos.​', null, 'Activo', null, null),
        (721, 1, '721', '% de Atención de solicitudes de soporte y requerimientos de Desarrollo de Software', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I43. Plan Estratégico de Tecnologías de la Información y las Comunicaciones (PETI)', null, 'Activo', null, null),
        (763, 1, '763', 'Porcentaje de cumplimiento evaluación de gestión por dependencias', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I40. Mejorar y proteger el valor de la Entidad con la evaluación independiente mediante servicios de aseguramiento y consultoría de los procesos de control, gestión de riesgos y gobierno institucional, lo que contribuye al logro de los objetivos.​', null, 'Activo', null, null),
        (722, 1, '722', '% de uso de los trámites implementados en la sede electrónica del SENA', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I43. Plan Estratégico de Tecnologías de la Información y las Comunicaciones (PETI)', null, 'Activo', null, null),
        (764, 1, '764', 'Porcentaje de cumplimiento trabajos de aseguramiento o consultoría a la  gestión de riesgos como ente auditable', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I40. Mejorar y proteger el valor de la Entidad con la evaluación independiente mediante servicios de aseguramiento y consultoría de los procesos de control, gestión de riesgos y gobierno institucional, lo que contribuye al logro de los objetivos.​', null, 'Activo', null, null),
        (863, 1, '863', 'Índice de gobierno digital ', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I43. Plan Estratégico de Tecnologías de la Información y las Comunicaciones (PETI)', null, 'Activo', null, null),
        (797, 1, '797', 'Porcentaje de Cumplimiento en la ejecución de los Informes de Cumplimiento y Seguimiento de Ley aprobados por el Comité Institucional de Coordinación de Control Interno', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I40. Mejorar y proteger el valor de la Entidad con la evaluación independiente mediante servicios de aseguramiento y consultoría de los procesos de control, gestión de riesgos y gobierno institucional, lo que contribuye al logro de los objetivos.​', null, 'Activo', null, null),
        (864, 1, '864', 'Porcentaje de implementación de  Plan Estratégico de Tecnologías de la Información y las Comunicaciones -­ PETI', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I43. Plan Estratégico de Tecnologías de la Información y las Comunicaciones (PETI)', null, 'Activo', null, null),
        (897, 1, '897', 'Porcentaje de cumplimiento en el número de seguimientos al estado de avance de los planes de mejoramiento (CGR)', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I40. Mejorar y proteger el valor de la Entidad con la evaluación independiente mediante servicios de aseguramiento y consultoría de los procesos de control, gestión de riesgos y gobierno institucional, lo que contribuye al logro de los objetivos.​', null, 'Activo', null, null),
        (580, 1, '580', 'Certificación - Formación  Complementaria', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I14. Implementación de acciones para el fortalecimiento de la calidad y pertinencia de la formación', null, 'Activo', null, null),
        (859, 1, '859', 'Mejora del índice de desempeño institucional del SENA', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I36. Actualizar el Sistema Integrado de Gestión y el mapa de procesos de la institución que promueva la efectividad, la calidad y la mejora continua, buscando la apropiación y su cumplimiento.', null, 'Activo', null, null),
        (711, 1, '711', 'Porcentaje de implementación del Pan de Sostenibilidad del Modelo Integrado de Planeación y Gestión – MIPG.', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I36. Actualizar el Sistema Integrado de Gestión y el mapa de procesos de la institución que promueva la efectividad, la calidad y la mejora continua, buscando la apropiación y su cumplimiento.', null, 'Activo', null, null),
        (712, 1, '712', 'Número de sesiones de fortalecimiento de la cultura de la anticipación, a través de la prospectiva y vigilancia', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I47. Actualizar e implementar el Modelo de Inteligencia Corporativa - Prospectiva', null, 'Activo', null, null),
        (895, 1, '895', 'Número de seguimientos al Plan Estratégico de la entidad', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'N/A', null, 'Activo', null, null),
        (852, 1, '852', 'Indice de permanencia de los instructores en las capacitaciones', '0', '2. MISIÓN', 'MI-O4. Innovar en la prestación integral de los servicios institucionales orientados a incrementar su calidad pertinencia y cobertura, con enfoque diferencial poblacional y territorial', '-', 'N/A', null, 'Activo', null, null),
        (896, 1, '896', 'Número de seguimientos a los planes de Acción y seguimiento de los CONPES (PAS)', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'N/A', null, 'Activo', null, null),
        (787, 1, '787', 'Porcentaje de satisfacción del instructor frente a las acciones de Capacitación', '0', '2. MISIÓN', 'MI-O4. Innovar en la prestación integral de los servicios institucionales orientados a incrementar su calidad pertinencia y cobertura, con enfoque diferencial poblacional y territorial', '-', 'N/A', null, 'Activo', null, null),
        (788, 1, '788', 'Porcentaje de la ejecución presupuestal en la formacion de instructores', '0', '2. MISIÓN', 'MI-O4. Innovar en la prestación integral de los servicios institucionales orientados a incrementar su calidad pertinencia y cobertura, con enfoque diferencial poblacional y territorial', '-', 'N/A', null, 'Activo', null, null),
        (789, 1, '789', 'Porcentaje de la cobertura de las Capacitaciones a los instructores.', '0', '2. MISIÓN', 'MI-O4. Innovar en la prestación integral de los servicios institucionales orientados a incrementar su calidad pertinencia y cobertura, con enfoque diferencial poblacional y territorial', '-', 'N/A', null, 'Activo', null, null),
        (853, 1, '853', 'Porcentaje de Cumplimiento del plan de trabajo previsto para el sistema de investigación, desarrollo tecnológico e innovación del SENA', '0', '2. MISIÓN', 'MI-O4. Innovar en la prestación integral de los servicios institucionales orientados a incrementar su calidad pertinencia y cobertura, con enfoque diferencial poblacional y territorial', '-', 'MI-O4-I27. Diseñar e implementar el plan de articulación de investigación e innovación institucional', null, 'Activo', null, null),
        (854, 1, '854', 'Número de Cupos de formación en articulación con la media - Convenio SENATEC', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I18. Habilidades Digitales - Convenio con MINTIC', null, 'Activo', null, null),
        (855, 1, '855', 'Número de Certificados de formación complementaria en Red TIC expedidos   ', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I19. Habilidades Digitales  - Plan para el seguimiento a la formación en habilidades digitales', null, 'Activo', null, null),
        (857, 1, '857', 'Número de cupos en formación profesional integral en municipios PDET', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'VA-O1-I3. Brindar  atención integral, diferencial  e incluyente  a las personas víctimas del conflicto armado y a los firmantes de paz, que contribuya a  la garantía de sus derechos sociales y económicos,  a la  transformación productiva y equitativa de l', null, 'Activo', null, null),
        (858, 1, '858', 'Número de Empresas y Asociaciones beneficiarias de las líneas de Fomento a la Innovación y Extensionismo Tecnológico.', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I13. Fortalecimiento de la atención empresarial', null, 'Activo', null, null),
        (804, 1, '804', 'Divulgar información de la gestión institucional para los grupos de valor internos del SENA', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I51. Fortalecer la dimensión información y comunicación a través  productos y canales de comunicación accesibles, acciones articuladas de imagen corporativa y  una imagen de marca SENA incluyente, sostenible  y transparente', null, 'Activo', null, null),
        (805, 1, '805', 'Divulgar información de la gestión  institucional para los grupos de valor externos del SENA', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I51. Fortalecer la dimensión información y comunicación a través  productos y canales de comunicación accesibles, acciones articuladas de imagen corporativa y  una imagen de marca SENA incluyente, sostenible  y transparente', null, 'Activo', null, null),
        (806, 1, '806', 'Productos digitales propios generados y publicados por la Regional', '0', '3. DESARROLLO INSTITUCIONAL', 'DI-O6. Fortalecer el modelo de operación institucional  para lograr una gestión efectiva orientada a  resultados, mediante la mejora continua de los procesos, el desarrollo de la cultura organizacional, y la gestión del talento humano.', '-', 'DI-O6-I51. Fortalecer la dimensión información y comunicación a través  productos y canales de comunicación accesibles, acciones articuladas de imagen corporativa y  una imagen de marca SENA incluyente, sostenible  y transparente', null, 'Activo', null, null),
        (898, 1, '823.', 'Número de acciones de divulgación de los resultados de los proyectos de I+D+i en cada regional', '0', '2. MISIÓN', 'MI-O4. Innovar en la prestación integral de los servicios institucionales orientados a incrementar su calidad pertinencia y cobertura, con enfoque diferencial poblacional y territorial', '-', 'MI-O4-I27. Diseñar e implementar el plan de articulación de investigación e innovación institucional', null, 'Activo', null, null),
        (899, 1, '824.', 'Porcentaje de entrega de apoyos de sostenimiento FIC', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'N/A', null, 'Activo', null, null),
        (900, 1, '825.', 'Porcentaje de entrega de apoyos de sostenimiento Regular', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'N/A', null, 'Activo', null, null),
        (817, 1, '817', 'Cupos Educación Superior (Tecnólogos)', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I14. Implementación de acciones para el fortalecimiento de la calidad y pertinencia de la formación', null, 'Activo', null, null),
        (73, 1, '73', 'Cupos programa Integración con la Educación Media "Tecnicos Laborales"', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I14. Implementación de acciones para el fortalecimiento de la calidad y pertinencia de la formación', null, 'Activo', null, null),
        (56, 1, '56', 'Cupos de formación Técnica Laboral y Otros SENA', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I14. Implementación de acciones para el fortalecimiento de la calidad y pertinencia de la formación', null, 'Activo', null, null),
        (818, 1, '818', 'Número de Personas con Formación Titulada del SENA', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I14. Implementación de acciones para el fortalecimiento de la calidad y pertinencia de la formación', null, 'Activo', null, null),
        (275, 1, '275', 'Cupos en programa Bilingûismo (incluidos en la Formación Titulada y Complementaria)', '0', '2. MISIÓN', 'MI-O4. Innovar en la prestación integral de los servicios institucionales orientados a incrementar su calidad pertinencia y cobertura, con enfoque diferencial poblacional y territorial', '-', 'MI-O4-I22. Promover los programas de multilingüismo en la formación profesional', null, 'Activo', null, null),
        (269, 1, '269', 'Aprendices en programa Bilingûismo (incluidos en la Formación Titulada y Complementaria)', '0', '2. MISIÓN', 'MI-O4. Innovar en la prestación integral de los servicios institucionales orientados a incrementar su calidad pertinencia y cobertura, con enfoque diferencial poblacional y territorial', '-', 'MI-O4-I22. Promover los programas de multilingüismo en la formación profesional', null, 'Activo', null, null),
        (53, 1, '53', 'Cupos  formación complementaria', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I14. Implementación de acciones para el fortalecimiento de la calidad y pertinencia de la formación', null, 'Activo', null, null),
        (18, 1, '18', 'Aprendices en formación complementaria', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I14. Implementación de acciones para el fortalecimiento de la calidad y pertinencia de la formación', null, 'Activo', null, null),
        (64, 1, '64', 'Cupos formación Integral Profesional ( Gran Total)', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I14. Implementación de acciones para el fortalecimiento de la calidad y pertinencia de la formación', null, 'Activo', null, null),
        (825, 1, '825', 'Número de cupos de formación profesional integral perteneciente a la estrategia campesena - matriculados ', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'VA-O1-I1. Implementar la estrategia de atención integral, diferencial  e incluyente para el sector de la economía campesina - CampeSENA', null, 'Activo', null, null),
        (819, 1, '819', 'Número de Certificaciones de Competencia Laboral expedidas en Economía campesina', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'VA-O1-I1. Implementar la estrategia de atención integral, diferencial  e incluyente para el sector de la economía campesina - CampeSENA', null, 'Activo', null, null),
        (812, 1, '812', 'Número de cupos de formación profesional integral pertenecientes al sector economía popular - matriculados', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'VA-O1-I2. Implementar la estrategia de atención integral, diferencial  e incluyente para el sector de la economía popular - Full Popular', null, 'Activo', null, null),
        (820, 1, '820', 'Número de Certificaciones de Competencia Laboral expedidas en Economía Popular', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'VA-O1-I2. Implementar la estrategia de atención integral, diferencial  e incluyente para el sector de la economía popular - Full Popular', null, 'Activo', null, null),
        (274, 1, '274', 'Cupos en formación virtual (incluye Bilinguismo) (incluidos en la Formación Titulada y Complementaria)', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I14. Implementación de acciones para el fortalecimiento de la calidad y pertinencia de la formación', null, 'Activo', null, null),
        (268, 1, '268', 'Aprendices en formación virtual (incluye Bilinguismo) (incluidos en la Formación Titulada y Complementaria)', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I14. Implementación de acciones para el fortalecimiento de la calidad y pertinencia de la formación', null, 'Activo', null, null),
        (814, 1, '814', 'Personas  víctimas  de  desplazamiento  forzado  que  acceden  a  programas  de  formación profesional integral', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'VA-O1-I3. Brindar  atención integral, diferencial  e incluyente  a las personas víctimas del conflicto armado y a los firmantes de paz, que contribuya a  la garantía de sus derechos sociales y económicos,  a la  transformación productiva y equitativa de l', null, 'Activo', null, null),
        (641, 1, '641', 'Cupos Total Poblaciones Vulnerables', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'N/A', null, 'Activo', null, null),
        (640, 1, '640', 'Aprendices Total Poblaciones Vulnerables', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'N/A', null, 'Activo', null, null),
        (816, 1, '816', 'Número de cupos de formación profesional integral para personas con discapacidad', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'VA-O1-I4. Implementar la Política Institucional de Atención a Personas con Discapacidad', null, 'Activo', null, null),
        (573, 1, '573', 'Retención - Técnica Laboral y  Otros', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I14. Implementación de acciones para el fortalecimiento de la calidad y pertinencia de la formación', null, 'Activo', null, null),
        (572, 1, '572', 'Retención - Educación Superior', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I14. Implementación de acciones para el fortalecimiento de la calidad y pertinencia de la formación', null, 'Activo', null, null),
        (574, 1, '574', 'Retención - Total Formación  Titulada', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I14. Implementación de acciones para el fortalecimiento de la calidad y pertinencia de la formación', null, 'Activo', null, null),
        (575, 1, '575', 'Retención - Formación  Complementaria', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I14. Implementación de acciones para el fortalecimiento de la calidad y pertinencia de la formación', null, 'Activo', null, null),
        (576, 1, '576', 'Retención - TOTAL Centros de Formación', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I14. Implementación de acciones para el fortalecimiento de la calidad y pertinencia de la formación', null, 'Activo', null, null),
        (578, 1, '578', 'Certificación - Técnica Laboral y  Otros', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I14. Implementación de acciones para el fortalecimiento de la calidad y pertinencia de la formación', null, 'Activo', null, null),
        (577, 1, '577', 'Certificación - Educación Superior', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I14. Implementación de acciones para el fortalecimiento de la calidad y pertinencia de la formación', null, 'Activo', null, null),
        (579, 1, '579', 'Certificación - Total Formación  Titulada', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I14. Implementación de acciones para el fortalecimiento de la calidad y pertinencia de la formación', null, 'Activo', null, null),
        (654, 1, '654', 'certificación - articulación con la media - técnicos', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I14. Implementación de acciones para el fortalecimiento de la calidad y pertinencia de la formación', null, 'Activo', null, null),
        (581, 1, '581', 'Certificación TOTAL  - Centros de Formación', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I14. Implementación de acciones para el fortalecimiento de la calidad y pertinencia de la formación', null, 'Activo', null, null),
        (565, 1, '565', 'Número de evaluaciones en competencias  laborales', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I15. Fortalecimiento de las acciones para el reconocimiento de los aprendizajes previos a través de la evaluación y certificación de competencias laborales y la comprobación de las cualificaciones, acorde con las políticas del Sistema Nacional de Cu', null, 'Activo', null, null),
        (566, 1, '566', 'Personas evaluadas en competencias laborales', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I15. Fortalecimiento de las acciones para el reconocimiento de los aprendizajes previos a través de la evaluación y certificación de competencias laborales y la comprobación de las cualificaciones, acorde con las políticas del Sistema Nacional de Cu', null, 'Activo', null, null),
        (821, 1, '821', 'Número de Certificaciones expedidas en competencias laborales', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I15. Fortalecimiento de las acciones para el reconocimiento de los aprendizajes previos a través de la evaluación y certificación de competencias laborales y la comprobación de las cualificaciones, acorde con las políticas del Sistema Nacional de Cu', null, 'Activo', null, null),
        (295, 1, '295', 'Personas Certificadas en Competencias Laborales.', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I15. Fortalecimiento de las acciones para el reconocimiento de los aprendizajes previos a través de la evaluación y certificación de competencias laborales y la comprobación de las cualificaciones, acorde con las políticas del Sistema Nacional de Cu', null, 'Activo', null, null),
        (596, 1, '596', 'Unidades productivas creadas (SER)', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I12. Diseñar e implementar acciones para el fortalecimiento de la calidad y pertinencia de emprendimiento', null, 'Activo', null, null),
        (597, 1, '597', 'Unidades productivas fortalecidas  (SER)', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'N/A', null, 'Activo', null, null),
        (822, 1, '822', 'Número de Aprendices SENA Con Contrato De Aprendizaje (Incluye contratos voluntarios)', '0', '1. VALOR', 'VA-O2. Potenciar el desarrollo sostenible de los territorios por medio del fortalecimiento de las actividades productivas de la  población,  las empresas, agremiaciones, asociaciones, cooperativas  y demás organizaciones, aportando a la transformación pro', '-', 'VA-O2-I16. Fortalecimiento de las estrategias de relacionamiento empresarial  para incrementar el número de empresas objeto de regulación, de acuerdo con lo establecido en la Ley 789 de 2002 y Decretos reglamentarios vigentes a través de las regionales.', null, 'Activo', null, null),
        (815, 1, '815', 'Número de planes de negocio formulados por víctimas del desplazamiento forzado.', '0', '1. VALOR', 'VA-O1. Promover la inclusión social y económica de la población, bajo un enfoque diferencial, fortaleciendo sus capacidades y las oportunidades de   empleabilidad, contribuyendo así al desarrollo equitativo de las comunidades a nivel urbano y rural, y al ', '-', 'VA-O1-I3. Brindar  atención integral, diferencial  e incluyente  a las personas víctimas del conflicto armado y a los firmantes de paz, que contribuya a  la garantía de sus derechos sociales y económicos,  a la  transformación productiva y equitativa de l', null, 'Activo', null, null),
        (784, 1, '784', 'Porcentaje de estrategias de Administración  Educativa para las Regionales y Centros de Formación Implementadas', '0', '2. MISIÓN', 'MI-O4. Innovar en la prestación integral de los servicios institucionales orientados a incrementar su calidad pertinencia y cobertura, con enfoque diferencial poblacional y territorial', '-', 'N/A', null, 'Activo', null, null),
        (795, 1, '795', 'Informe de seguimiento a los centros de formación con relación a materiales de formación, EPP´s y software  requeridos en la ejecución de los programas de formación del SENA.', '0', '2. MISIÓN', 'MI-O4. Innovar en la prestación integral de los servicios institucionales orientados a incrementar su calidad pertinencia y cobertura, con enfoque diferencial poblacional y territorial', '-', 'N/A', null, 'Activo', null, null),
        (766, 1, '766', 'Consultas de los recursos físicos y digitales, dispuestos en la Biblioteca, realizadas por los usuarios sena del centro Formación', '0', '2. MISIÓN', 'MI-O4. Innovar en la prestación integral de los servicios institucionales orientados a incrementar su calidad pertinencia y cobertura, con enfoque diferencial poblacional y territorial', '-', 'N/A', null, 'Activo', null, null),
        (823, 1, '823', 'Porcentaje de Aprendices del Centro en fichas en ejecución en etapa productiva que tienen únicamente por evaluar el RAP de Etapa Productiva', '0', '2. MISIÓN', 'MI-O4. Innovar en la prestación integral de los servicios institucionales orientados a incrementar su calidad pertinencia y cobertura, con enfoque diferencial poblacional y territorial', '-', 'N/A', null, 'Activo', null, null),
        (768, 1, '768', 'Porcentaje de Fichas de formación titulada del Centro con registro de entrega de materiales de formación durante la vigencia', '0', '2. MISIÓN', 'MI-O4. Innovar en la prestación integral de los servicios institucionales orientados a incrementar su calidad pertinencia y cobertura, con enfoque diferencial poblacional y territorial', '-', 'N/A', null, 'Activo', null, null),
        (771, 1, '771', 'Porcentaje de Fichas correctamente programadas', '0', '2. MISIÓN', 'MI-O4. Innovar en la prestación integral de los servicios institucionales orientados a incrementar su calidad pertinencia y cobertura, con enfoque diferencial poblacional y territorial', '-', 'N/A', null, 'Activo', null, null),
        (824, 1, '824', 'Porcentaje de Grupos (fichas) de formacion titulada con mas del 80% de horas programas de acuerdo al diseño curricular ', '0', '2. MISIÓN', 'MI-O4. Innovar en la prestación integral de los servicios institucionales orientados a incrementar su calidad pertinencia y cobertura, con enfoque diferencial poblacional y territorial', '-', 'N/A', null, 'Activo', null, null),
        (826, 1, '826', 'Número de Documentos de investigación elaborados', '0', '2. MISIÓN', 'MI-O4. Innovar en la prestación integral de los servicios institucionales orientados a incrementar su calidad pertinencia y cobertura, con enfoque diferencial poblacional y territorial', '-', 'MI-O4-I27. Diseñar e implementar el plan de articulación de investigación e innovación institucional', null, 'Activo', null, null),
        (813, 1, '813', 'Número de  Campesinos atendidos en el programa de emprendimiento ', null, null, null, '-', null, null, 'Activo', null, null);